name: Monorepo Test and format
on:
  push:
    branches: [master, feature, chore, bugfix, hotfix, release, main, spike]

  pull_request:
    branches:
      - master
jobs:
  integration_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm run install:workflow
      - run: npm run build
      - run: npm run test
      - run: npm run format
