name: Monorepo Test and format
on:
  push:
    branches: 
      - '**' 

jobs:
  integration_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm run install:all
      - run: npm run test
      - run: npm run format
